import { useState, useEffect, useRef, useCallback } from 'react';
import { Client } from '@stomp/stompjs';
import SockJS from 'sockjs-client';
import { sendMessageRest } from '../services/chatApi.js';
import { useAuth } from '../context/AuthContext.jsx';

const WS_URL = import.meta.env.VITE_WS_BASE_URL || 'http://localhost:8080/ws/sockjs';

/**
 * Hook that manages the STOMP WebSocket connection and real-time message delivery.
 *
 * @param {number|null}   conversationId  The currently selected conversation.
 * @param {function}      onMessage       Called with a MessageDto when a new message arrives.
 * @returns {{
 *   connected: boolean,
 *   sendMessage: function,
 *   wsError: string|null
 * }}
 */
export function useChat(conversationId, onMessage) {
  const { currentUser, token } = useAuth();
  const [connected, setConnected] = useState(false);
  const [wsError, setWsError] = useState(null);
  const clientRef = useRef(null);
  const subscriptionRef = useRef(null);
  const onMessageRef = useRef(onMessage);

  // Keep onMessage ref current without triggering reconnects
  useEffect(() => { onMessageRef.current = onMessage; }, [onMessage]);

  // ── Connect / disconnect lifecycle ────────────────────────────────────────
  useEffect(() => {
    if (!currentUser?.username && !currentUser?.email) return;

    const client = new Client({
      webSocketFactory: () => new SockJS(WS_URL),
      connectHeaders: token ? { Authorization: `Bearer ${token}` } : {},
      reconnectDelay: 5000,
      onConnect: () => {
        setConnected(true);
        setWsError(null);

        // Subscribe to server-sent error messages (validation/auth failures)
        client.subscribe('/user/queue/errors', (frame) => {
          try {
            const payload = JSON.parse(frame.body);
            setWsError(payload.error || 'Server error');
          } catch {
            setWsError('Server error');
          }
        });
      },
      onDisconnect: () => {
        setConnected(false);
      },
      onStompError: (frame) => {
        setWsError(frame.headers?.message || 'WebSocket error');
        setConnected(false);
      },
      onWebSocketError: () => {
        setWsError('WebSocket connection failed — retrying…');
        setConnected(false);
      },
    });

    client.activate();
    clientRef.current = client;

    return () => {
      subscriptionRef.current?.unsubscribe();
      subscriptionRef.current = null;
      client.deactivate();
      clientRef.current = null;
      setConnected(false);
    };
  }, [currentUser?.username, token]);

  // ── Subscribe / unsubscribe when conversation changes ─────────────────────
  useEffect(() => {
    const client = clientRef.current;
    if (!client || !connected || conversationId == null) return;

    // Unsubscribe from the previous conversation
    subscriptionRef.current?.unsubscribe();

    subscriptionRef.current = client.subscribe(
      `/topic/conversations/${conversationId}`,
      (frame) => {
        try {
          const msg = JSON.parse(frame.body);
          onMessageRef.current?.(msg);
        } catch {
          // malformed frame — ignore
        }
      }
    );

    return () => {
      subscriptionRef.current?.unsubscribe();
      subscriptionRef.current = null;
    };
  }, [connected, conversationId]);

  /**
   * Sends a message to the current conversation.
   *
   * Primary path: STOMP /app/chat.send
   * Fallback:     REST POST /api/conversations/{id}/messages (when WS is disconnected)
   *
   * @param {string} content
   * @param {string} clientMsgId  UUID (v4) generated by the caller.
   * @returns {Promise<Object|null>}  Resolved MessageDto on REST fallback; null on WS send.
   */
  const sendMessage = useCallback(async (content, clientMsgId) => {
    const client = clientRef.current;
    if (client?.connected && conversationId != null) {
      client.publish({
        destination: '/app/chat.send',
        body: JSON.stringify({ conversationId, content, clientMsgId }),
      });
      return null; // real-time response arrives via subscription
    }

    // WebSocket unavailable — fall back to REST
    return sendMessageRest(conversationId, content, clientMsgId);
  }, [conversationId]);

  return { connected, sendMessage, wsError };
}
