import api from './api.js';

/**
 * Chat module API service.
 * All calls go through the shared Axios instance which adds the Authorization header.
 */

// ── Conversations ─────────────────────────────────────────────────────────────

/** GET /api/conversations — list all conversations for the current user. */
export const getConversations = () =>
  api.get('/conversations').then((r) => r.data);

/**
 * POST /api/conversations — find or create a 1-to-1 conversation.
 * @param {number} targetUserId
 */
export const createConversation = (targetUserId) =>
  api.post('/conversations', { targetUserId }).then((r) => r.data);

// ── Messages ──────────────────────────────────────────────────────────────────

/**
 * GET /api/conversations/{id}/messages?page={page}
 * @param {number} conversationId
 * @param {number} page  Zero-based page index (default 0).
 */
export const getMessages = (conversationId, page = 0) =>
  api.get(`/conversations/${conversationId}/messages`, { params: { page } }).then((r) => r.data);

/**
 * POST /api/conversations/{id}/messages — REST fallback for sending a message
 * when the WebSocket is unavailable.
 * @param {number} conversationId
 * @param {string} content
 * @param {string} clientMsgId  UUID generated by the client.
 */
export const sendMessageRest = (conversationId, content, clientMsgId) =>
  api.post(`/conversations/${conversationId}/messages`, { content, clientMsgId }).then((r) => r.data);

// ── Users ─────────────────────────────────────────────────────────────────────

/**
 * GET /api/users — list all users to start a new conversation with.
 * TODO: This endpoint will be provided by Aman's auth/profile module.
 * Until it exists, the "New Conversation" dialog is hidden.
 */
export const getUsers = () =>
  api.get('/users').then((r) => r.data);
