import api from './api.js';

/**
 * Chat module API service.
 * All calls go through the shared Axios instance which adds the Authorization header.
 */

// ── Conversations ─────────────────────────────────────────────────────────────

/** GET /api/conversations — list all conversations for the current user. */
export const getConversations = () =>
  api.get('/conversations').then((r) => r.data);

/**
 * POST /api/conversations — find or create a 1-to-1 conversation.
 * @param {number} targetUserId
 */
export const createConversation = (targetUserId) =>
  api.post('/conversations', { targetUserId }).then((r) => r.data);

// ── Messages ──────────────────────────────────────────────────────────────────

/**
 * GET /api/conversations/{id}/messages?page={page}
 * @param {number} conversationId
 * @param {number} page  Zero-based page index (default 0).
 */
export const getMessages = (conversationId, page = 0) =>
  api.get(`/conversations/${conversationId}/messages`, { params: { page } }).then((r) => r.data);

/**
 * POST /api/conversations/{id}/messages — REST fallback for sending a message
 * when the WebSocket is unavailable.
 * @param {number} conversationId
 * @param {string} content
 * @param {string} clientMsgId  UUID generated by the client.
 */
export const sendMessageRest = (conversationId, content, clientMsgId) =>
  api.post(`/conversations/${conversationId}/messages`, { content, clientMsgId }).then((r) => r.data);

// ── Users ─────────────────────────────────────────────────────────────────────

/**
 * GET /api/conversations/users/search?q={query}
 * Searches for users by name or email for the "New Conversation" dialog.
 * @param {string} query  Search fragment (name or email).
 */
export const searchUsers = (query) =>
  api.get('/conversations/users/search', { params: { q: query } }).then((r) => r.data);

// ── Presence ──────────────────────────────────────────────────────────────────

/**
 * GET /api/presence/{userId}
 * Retrieves presence status ('ONLINE' | 'OFFLINE') for a user.
 * @param {number} userId
 */
export const getUserPresence = (userId) =>
  api.get(`/presence/${userId}`).then((r) => r.data);

/**
 * GET /api/presence/batch?userIds=1,2,3
 * Retrieves presence status for a list of user IDs.
 * @param {number[]} userIds
 */
export const getBatchPresence = (userIds) => {
  if (!userIds || userIds.length === 0) return Promise.resolve({});
  return api.get('/presence/batch', { params: { userIds: userIds.join(',') } }).then((r) => r.data);
};

